# fly.toml app configuration file generated for qubit-workshop-2023 on 2023-09-25T12:22:40+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "qubit-workshop-2023"
primary_region = "ams"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
